TASK-40995:External user flag is still displayed next to the user fullname
exoplatform/chat-application pull request #329
Opened 2021-08-30 16:24 UTC by GouadriaHanen

when adding a user to  "External group " an external flag must be displayed next to his name in chat room and chat drawer 
the External Flag isn't always displayed because in the actual behavior    setting user property is set when the user log in  and not updated when removed from 
Added a listener from MembershipEventListener to update the user enabled property one added or removed from "External group "

2021-08-30 16:30 UTC, GouadriaHanen commented
related PR : https://github.com/Meeds-io/gatein-portal/pull/273

2021-08-31 07:43 UTC, rdenarie requested changes
Can you rebase your PR in order to have only your commit ?

In addition, as the call to ServerBootstrap.setExternalUser is done when the user's group changes, should we remove the listener UserLoginListener ?

2021-08-31 08:58 UTC, GouadriaHanen commented
> Can you rebase your PR in order to have only your commit ?
> 
> In addition, as the call to ServerBootstrap.setExternalUser is done when the user's group changes, should we remove the listener UserLoginListener ?

 UserLoginListener isn't just for setting external property it is also for enabled and other properties! we can remove setting external or change behavior of the listener!

2021-08-31 09:10 UTC, rdenarie commented
> > Can you rebase your PR in order to have only your commit ?
> > In addition, as the call to ServerBootstrap.setExternalUser is done when the user's group changes, should we remove the listener UserLoginListener ?
> 
> UserLoginListener isn't just for setting external property it is also for enabled and other properties! we can remove setting external or change behavior of the listener!

Yes you are right. I think we should remove stuff related to externaluser is UserLoginListener as you "move" it in another listener

2021-08-31 09:31 UTC, rdenarie requested changes
Can you fix the 4 codes smells targeted by sonar ? 
It is unused imports.

2021-08-31 10:12 UTC, rdenarie requested changes
There is one more code smell to fix

2021-08-31 11:43 UTC, rdenarie approved these changes

2021-08-31 11:47 UTC, merged