MAINT-50584: Fix users and rooms avatar urls retrieving
exoplatform/chat-application pull request #380
Opened 2021-10-28 12:11 UTC by hakermi

**ISSUE** : when selecting a room in the full chat application and than select a second room, the room details always show the first selected room avatar because of the render before the promise resolving. 
**FIX**: refactor the room avatar retrieving in the chat app by replacing the sync front rest calls by a retrieving in the back-end.

2021-10-28 16:56 UTC, AzmiTouil requested changes

2021-10-28 16:56 UTC, AzmiTouil commented on services/src/main/java/org/exoplatform/addons/chat/api/UserRestService.java
> +    String avatarUrl = userIdentity.getProfile().getAvatarUrl();
```suggestion
    String avatarUrl = userIdentity.getProfile() != null ? userIdentity.getProfile().getAvatarUrl() : null;
```

2021-10-29 17:08 UTC, hakermi commented on services/src/main/java/org/exoplatform/addons/chat/api/UserRestService.java
> +    String avatarUrl = userIdentity.getProfile().getAvatarUrl();
done

2021-11-01 09:05 UTC, AzmiTouil approved these changes
LGTM

2021-11-01 09:07 UTC, merged